[package]
name = "4812571/line-asset-builder"
version = "0.1.8"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
WeightedChoice = "4812571/weighted-choice@1.0.2"